# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'create_account.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 653)
        MainWindow.setStyleSheet("background-color:rgb(172, 255, 253)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 30, 591, 481))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.titlelabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.titlelabel.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.titlelabel.setFont(font)
        self.titlelabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.titlelabel.setAutoFillBackground(False)
        self.titlelabel.setStyleSheet("background-color:rgb(178, 186, 255)\n"
"")
        self.titlelabel.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhUppercaseOnly)
        self.titlelabel.setFrameShape(QtWidgets.QFrame.Panel)
        self.titlelabel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.titlelabel.setLineWidth(5)
        self.titlelabel.setTextFormat(QtCore.Qt.RichText)
        self.titlelabel.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.titlelabel.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.titlelabel.setObjectName("titlelabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.titlelabel)
        self.usernameLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.usernameLabel.setFont(font)
        self.usernameLabel.setObjectName("usernameLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.usernameLabel)
        self.usernameline = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.usernameline.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.usernameline.setObjectName("usernameline")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.usernameline)
        self.nameLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.nameLabel.setFont(font)
        self.nameLabel.setObjectName("nameLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.nameLabel)
        self.nameline = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.nameline.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.nameline.setObjectName("nameline")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.nameline)
        self.surnameLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.surnameLabel.setFont(font)
        self.surnameLabel.setObjectName("surnameLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.surnameLabel)
        self.surnameline = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.surnameline.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.surnameline.setObjectName("surnameline")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.surnameline)
        self.genderLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.genderLabel.setFont(font)
        self.genderLabel.setObjectName("genderLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.genderLabel)
        self.marriageLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.marriageLabel.setFont(font)
        self.marriageLabel.setObjectName("marriageLabel")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.marriageLabel)
        self.emailLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.emailLabel.setFont(font)
        self.emailLabel.setObjectName("emailLabel")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.emailLabel)
        self.emailline = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.emailline.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.emailline.setObjectName("emailline")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.emailline)
        self.confirmemailLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.confirmemailLabel.setFont(font)
        self.confirmemailLabel.setObjectName("confirmemailLabel")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.confirmemailLabel)
        self.confirmemailline = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.confirmemailline.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.confirmemailline.setObjectName("confirmemailline")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.confirmemailline)
        self.passwoordLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.passwoordLabel.setFont(font)
        self.passwoordLabel.setObjectName("passwoordLabel")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.passwoordLabel)
        self.passwoordline = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.passwoordline.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.passwoordline.setObjectName("passwoordline")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.passwoordline)
        self.confirmpassLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.confirmpassLabel.setFont(font)
        self.confirmpassLabel.setObjectName("confirmpassLabel")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.confirmpassLabel)
        self.conformpassline = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.conformpassline.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.conformpassline.setObjectName("conformpassline")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.conformpassline)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.cancelpushButton = QtWidgets.QPushButton(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.cancelpushButton.setFont(font)
        self.cancelpushButton.setStyleSheet("background-color:rgb(197, 0, 0)")
        self.cancelpushButton.setObjectName("cancelpushButton")
        self.gridLayout_2.addWidget(self.cancelpushButton, 0, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 0, 1, 1)
        self.createaccountpushButton = QtWidgets.QPushButton(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.createaccountpushButton.setFont(font)
        self.createaccountpushButton.setStyleSheet("background-color:rgb(85, 255, 127)")
        self.createaccountpushButton.setObjectName("createaccountpushButton")
        self.gridLayout_2.addWidget(self.createaccountpushButton, 0, 1, 1, 1)
        self.formLayout.setLayout(11, QtWidgets.QFormLayout.SpanningRole, self.gridLayout_2)
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setObjectName("formLayout_4")
        self.readandacceptcheckBox = QtWidgets.QCheckBox(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.readandacceptcheckBox.setFont(font)
        self.readandacceptcheckBox.setObjectName("readandacceptcheckBox")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.readandacceptcheckBox)
        self.readandaccepttextEdit = QtWidgets.QTextEdit(self.formLayoutWidget)
        self.readandaccepttextEdit.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.readandaccepttextEdit.setObjectName("readandaccepttextEdit")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.readandaccepttextEdit)
        self.formLayout.setLayout(10, QtWidgets.QFormLayout.SpanningRole, self.formLayout_4)
        self.gendergroupBox = QtWidgets.QGroupBox(self.formLayoutWidget)
        self.gendergroupBox.setObjectName("gendergroupBox")
        self.formLayout_3 = QtWidgets.QFormLayout(self.gendergroupBox)
        self.formLayout_3.setContentsMargins(1, 10, -1, -1)
        self.formLayout_3.setObjectName("formLayout_3")
        self.femaleradioButton = QtWidgets.QRadioButton(self.gendergroupBox)
        self.femaleradioButton.setObjectName("femaleradioButton")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.femaleradioButton)
        self.maleradioButton = QtWidgets.QRadioButton(self.gendergroupBox)
        self.maleradioButton.setObjectName("maleradioButton")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.maleradioButton)
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.gendergroupBox)
        self.marriagegroupBox = QtWidgets.QGroupBox(self.formLayoutWidget)
        self.marriagegroupBox.setObjectName("marriagegroupBox")
        self.formLayout_6 = QtWidgets.QFormLayout(self.marriagegroupBox)
        self.formLayout_6.setContentsMargins(1, 10, 1, 1)
        self.formLayout_6.setObjectName("formLayout_6")
        self.marriedradioButton = QtWidgets.QRadioButton(self.marriagegroupBox)
        self.marriedradioButton.setObjectName("marriedradioButton")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.marriedradioButton)
        self.singleradioButton = QtWidgets.QRadioButton(self.marriagegroupBox)
        self.singleradioButton.setObjectName("singleradioButton")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.singleradioButton)
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.marriagegroupBox)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionClear = QtWidgets.QAction(MainWindow)
        self.actionClear.setObjectName("actionClear")
        self.action_Ctrl_Q = QtWidgets.QAction(MainWindow)
        self.action_Ctrl_Q.setObjectName("action_Ctrl_Q")
        self.actionZoom_In_Ctrl_1 = QtWidgets.QAction(MainWindow)
        self.actionZoom_In_Ctrl_1.setObjectName("actionZoom_In_Ctrl_1")
        self.actionZoom_Out_Ctrl_0 = QtWidgets.QAction(MainWindow)
        self.actionZoom_Out_Ctrl_0.setObjectName("actionZoom_Out_Ctrl_0")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionInfo = QtWidgets.QAction(MainWindow)
        self.actionInfo.setObjectName("actionInfo")
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionClear)
        self.menuFile.addAction(self.action_Ctrl_Q)
        self.menuView.addAction(self.actionZoom_In_Ctrl_1)
        self.menuView.addAction(self.actionZoom_Out_Ctrl_0)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionInfo)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.titlelabel.setText(_translate("MainWindow", "CREATE A NEW ACCOUNT"))
        self.usernameLabel.setText(_translate("MainWindow", "Username"))
        self.nameLabel.setText(_translate("MainWindow", "Name"))
        self.surnameLabel.setText(_translate("MainWindow", "Surname"))
        self.genderLabel.setText(_translate("MainWindow", "Gender"))
        self.marriageLabel.setText(_translate("MainWindow", "Marriage Status"))
        self.emailLabel.setText(_translate("MainWindow", "e-mail"))
        self.confirmemailLabel.setText(_translate("MainWindow", "Confirm e-mail"))
        self.passwoordLabel.setText(_translate("MainWindow", "Passwoord"))
        self.confirmpassLabel.setText(_translate("MainWindow", "Confirm Passwoord"))
        self.cancelpushButton.setText(_translate("MainWindow", "Cancel"))
        self.createaccountpushButton.setText(_translate("MainWindow", "Create My Account"))
        self.readandacceptcheckBox.setText(_translate("MainWindow", "Read and Accepted"))
        self.readandaccepttextEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'sans-serif\'; font-size:8pt; color:#222222; background-color:#ffffff;\">As rights vary by country and jurisdiction, a work may be subject to rights in one country and be in the public domain in another. Some rights depend on registrations on a country-by-country basis, and the absence of registration in a particular country, if required, gives rise to public-domain status for a work in that country. The term public domain may also be interchangeably used with other imprecise or undefined terms such as the &quot;</span><a href=\"https://en.wikipedia.org/wiki/Public_sphere\"><span style=\" font-family:\'sans-serif\'; font-size:8pt; text-decoration: underline; color:#0b0080; background-color:#ffffff;\">public sphere</span></a><span style=\" font-family:\'sans-serif\'; font-size:8pt; color:#222222; background-color:#ffffff;\">&quot; or &quot;</span><a href=\"https://en.wikipedia.org/wiki/Commons\"><span style=\" font-family:\'sans-serif\'; font-size:8pt; text-decoration: underline; color:#0b0080; background-color:#ffffff;\">commons</span></a><span style=\" font-family:\'sans-serif\'; font-size:8pt; color:#222222; background-color:#ffffff;\">&quot;, including concepts such as the &quot;commons of the mind&quot;, the &quot;intellectual commons&quot;, and the &quot;information commons&quot;.</span></p></body></html>"))
        self.femaleradioButton.setText(_translate("MainWindow", "Female"))
        self.maleradioButton.setText(_translate("MainWindow", "Male"))
        self.marriedradioButton.setText(_translate("MainWindow", "Married"))
        self.singleradioButton.setText(_translate("MainWindow", "Single"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionSave.setText(_translate("MainWindow", "Save   (Ctrl+S)"))
        self.actionClear.setText(_translate("MainWindow", "Clear   (Ctrl+C)"))
        self.action_Ctrl_Q.setText(_translate("MainWindow", "Quit   (Ctrl+Q)"))
        self.actionZoom_In_Ctrl_1.setText(_translate("MainWindow", "Zoom In   (Ctrl+1)"))
        self.actionZoom_Out_Ctrl_0.setText(_translate("MainWindow", "Zoom Out   (Ctrl+0)"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionInfo.setText(_translate("MainWindow", "Info"))

